import NavBar from "@/components/NavBar";
import type { Metadata } from "next";
import "./globals.css";
import VegetableProvider from "./context/vegetableProvider";

const font = ({ subsets: ["SF-Pro"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}><VegetableProvider><NavBar />{children}</VegetableProvider></body>
    </html>
  );
}
