import NavBar from "@/components/NavBar";
import type { Metadata } from "next";
import "./globals.css";
import VegetableProvider from "./context/vegetableProvider";
import { ChakraProvider } from "@chakra-ui/react";
import CartProvider from "./context/cartProvider";

const font = ({ subsets: ["SF-Pro"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body><ChakraProvider><VegetableProvider><CartProvider><NavBar />{children}</CartProvider></VegetableProvider></ChakraProvider></body>
    </html>
  );
}
